import { useSession } from 'next-auth/react';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import styles from '../styles/Home.module.css';

export default function Home() {
	const { data: session } = useSession();

	// console.log(session);

	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.main}>
				<h1>NextAuth + MongoDB + ReduxToolkit</h1>
				<br />
				{!session && (
					<Link href="/auth/signin">
						<button

						// onClick={() => signIn()}
						>
							Sign in
						</button>
					</Link>
				)}
			</main>
		</div>
	);
}
