import Head from 'next/head';
import Image from 'next/image';
import { useState } from 'react';
import { useSelector, useDispatch } from 'react-redux';
import {
	addProduct,
	setProductInfo,
	deleteProduct,
	deleteSelectedProducts
} from '../redux/features/productSlice';
import styles from '../styles/Home.module.css';

export default function Home() {
	// console.log(selectedItems);

	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.main}>
				<h1>NextAuth + MongoDB + ReduxToolkit</h1>
			</main>
		</div>
	);
}
